library(tidyverse)

survived <- model_army_all %>% filter(death == 0)
died     <- model_army_all %>% filter(death == 1)
n_surv   <- nrow(survived)
n_died   <- nrow(died)
n_tot    <- nrow(model_army_all)

ms <- function(x) sprintf("%.2f (%.2f)", mean(x, na.rm=TRUE), sd(x, na.rm=TRUE))
np <- function(x, n) sprintf("%d (%.1f%%)", sum(x, na.rm=TRUE), sum(x, na.rm=TRUE)/n*100)

cat("\nCharacteristic                             Survived              Died                  Total\n")
cat(strrep("-", 95), "\n")
cat(sprintf("%-43s %-22s %-22s %-22s\n", "n", n_surv, n_died, n_tot))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "Cohort 1948, n (%)", np(survived$cohort==1948, n_surv), np(died$cohort==1948, n_died), np(model_army_all$cohort==1948, n_tot)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "Cohort 1953, n (%)", np(survived$cohort==1953, n_surv), np(died$cohort==1953, n_died), np(model_army_all$cohort==1953, n_tot)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "Child cognitive level, mean (SD)", ms(survived$child_g_z), ms(died$child_g_z), ms(model_army_all$child_g_z)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "Army g age 18, mean (SD)", ms(survived$army_g_z), ms(died$army_g_z), ms(model_army_all$army_g_z)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "Adolescent cognitive change, mean (SD)", ms(survived$army_g_resid), ms(died$army_g_resid), ms(model_army_all$army_g_resid)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "Parental education (z), mean (SD)", ms(survived$parentedu_mean_z), ms(died$parentedu_mean_z), ms(model_army_all$parentedu_mean_z)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "Age at death, mean (SD)", "—", ms(died$stop_age), ms(model_army_all$stop_age[model_army_all$death==1])))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "Follow-up years, mean (SD)", ms(survived$stop_age - survived$start_age), ms(died$stop_age - died$start_age), ms(model_army_all$stop_age - model_army_all$start_age)))
cat(strrep("-", 95), "\n")
cat(sprintf("%-43s %-22s %-22s %-22s\n", "Deaths by cause, n (% of sample)", "", "", ""))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "  Cancer",         "—", np(died$ev_cancer,       n_tot), np(model_army_all$ev_cancer,       n_tot)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "  Cardiovascular", "—", np(died$ev_cvd,           n_tot), np(model_army_all$ev_cvd,           n_tot)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "  Respiratory",    "—", np(died$ev_resp,          n_tot), np(model_army_all$ev_resp,          n_tot)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "  External",       "—", np(died$ev_external,      n_tot), np(model_army_all$ev_external,      n_tot)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "    Accidental",   "—", np(died$ev2_accidental,   n_tot), np(model_army_all$ev2_accidental,   n_tot)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "    Suicide",      "—", np(died$ev_suicide,       n_tot), np(model_army_all$ev_suicide,       n_tot)))
cat(sprintf("%-43s %-22s %-22s %-22s\n", "  Other",          "—", np(died$ev_other,         n_tot), np(model_army_all$ev_other,         n_tot)))
cat(strrep("-", 95), "\n")
